---
deployment:
 tasks:
 - export DEPLOYPATH=/home/superwor/public_html
 - /bin/cp -r index.php $DEPLOYPATH
 - /bin/cp -r pricelist.php $DEPLOYPATH
 - /bin/cp -r scripts.js $DEPLOYPATH
 - /bin/cp -r connections/pricelistpost.php $DEPLOYPATH