---
deployment:
 tasks:
 - export DEPLOYPATH=/home/superwor/public_html
 - /bin/cp index.php $DEPLOYPATH
 - /bin/cp pricelist.php $DEPLOYPATH
 - /bin/cp scripts.js $DEPLOYPATH
 - /bin/cp connections $DEPLOYPATH